README.md
bash_unit
tests/test_bash_unit.sh

It is useful to have an `assert_not_equals` function because otherwise the comparison has to be manually written using `assert`.
I have run the unit tests with success.
I did not bother to get `doctoc` and just manually added the TOC entry. I tried to run `./test_doc.sh` (since there were no bash_unit test functions in that script) after copying `README.md` into the script folder, but that created many folders in `/tmp` and ran a long time until I interrupted it. Then I gave up on that, so it still has to be tested.

assert_not_equals

---

bash_unit

The colors were not working in my Macbook.  Found that \e is not supported, so I updated to use printf + octal representation of escape

Fixed coloring for Mac OSX Bash

---

install.sh

cp on MacOS doesn't support the `-t` option. Rewrote call to find to use `--exec` and skip the pipe to `xargs`. Also quoted paths, because there could be spaces at any time.

FIX #22 Correct install.sh to work on MacOS.

---

README.md

The "fake function" header was missing a space " ", which messed up formatting.
This PR fixes that.

Fixes typo in README file.

---

install.sh

Remove this warning when installing bash_unit on Fedora 25 or Centos 7:
```
find: warning: you have specified the -maxdepth option after a non-option argument -type, but options are not positional (-maxdepth affects tests specified before it as well as those specified after it).  Please specify options before other arguments.
```

Remove warning with find command

---

README.adoc

Because *bash_unit* has been added to nixpkgs: https://github.com/NixOS/nixpkgs/pull/76941 .

Add installation instruction for Nix/NixOS

---

README.adoc
bash_unit
tests/test_cli.sh
tests/test_core.sh

Makes it easier to identify which test suite a test case message belongs to. Example:
* Before
```
Running tests in test_cli.sh
Running test_bash_unit_runs_teardown_even_in_case_of_failure... SUCCESS
Running test_bash_unit_succeed_when_no_failure_even_if_no_teardown... SUCCESS
Running test_display_usage_when_test_file_does_not_exist... SUCCESS
Running test_exit_code_not_0_in_case_of_failure... SUCCESS
Running tests in test_doc.sh
Running test_block_1... SUCCESS
Running test_block_10... SUCCESS
Running test_block_11... SUCCESS
Running test_block_12... SUCCESS
Running tests in test_tap_format
Running test_assertion_message_is_tap_formatted... SUCCESS
Running test_bash_unit_accepts_tap_format_option... SUCCESS
Running test_bash_unit_rejects_invalid_format... SUCCESS
Running …
```

Indent log messages for single test cases

---

README.adoc
bash_unit
tests/test_cli.sh

This change makes it possible to double-click the test case name so it can be inserted elsewhere with the middle mouse button. Without the space, the "..." would also have been selected/copied/inserted.
Before:
```
Running tests in test_tap_format
Running test_assertion_message_is_tap_formatted... SUCCESS ✓
Running test_bash_unit_accepts_tap_format_option... SUCCESS ✓
Running test_bash_unit_rejects_invalid_format... SUCCESS ✓
Running test_multi_lines_assertion_message_is_tap_formatted... SUCCESS ✓
Running test_tap_format_for_failing_test_with_stdout_stderr_outputs... SUCCESS ✓
Running test_tap_format_for_one_failing_test... SUCCESS ✓
Running test_tap_format_for_one_pending_test... SUCCESS ✓
Running test_tap_format_for_one_succesfull_test... SUCCESS ✓
```
Now:
```
Running tests in …
```

In log output, add a space before the "..."

---

README.adoc
bash_unit

Test files are always executed in the order in which they are specified on the command line. If `-r` is specified, the test cases within a file are executed in random order.

Add option -r: Execute test cases in random order

---

README.adoc

I took the liberty of adding bash_unit to [Homebrew](https://brew.sh) - a popular package manager mainly used in the MacOS ecosystem. This PR adds a reference to it in the readme.

doc: add brew installation notes

---

README.adoc

Issue is related to a training space generated by the test, which was missing in the output section in the README document.

fix for issue #76 missing trailing space in output section

---

README.adoc
bash_unit
tests/test_cli.sh
tests/test_core.sh
tests/test_doc.sh

Example:
```
$ ./bash_unit tests/test_tap_format
Running tests in tests/test_tap_format
/home/wolfram/src/bash_unit/tests
Running test_assertion_message_is_tap_formatted ... SUCCESS ✓
Running test_bash_unit_accepts_tap_format_option ... SUCCESS ✓
Running test_bash_unit_rejects_invalid_format ... SUCCESS ✓
Running test_multi_lines_assertion_message_is_tap_formatted ... SUCCESS ✓
Running test_tap_format_for_failing_test_with_stdout_stderr_outputs ... SUCCESS ✓
Running test_tap_format_for_one_failing_test ... SUCCESS ✓
Running test_tap_format_for_one_pending_test ... SUCCESS ✓
Running test_tap_format_for_one_succesfull_test ... SUCCESS ✓
Overall result: PASS ✓
```
So when you've got a lot of tests (more than a screenful) you don't have to scroll up or check $? to tell if any test has failed. …

Output "Overall result" line at the end

---

README.adoc
bash_unit
docs/man/man1/bash_unit.1
release
tests/test_core.sh

a regular action when testing scripts is to test generated files to match a valid content. This is often done using assert with the following line:
`assert "diff 'path/to/exepected file' 'path/to/generated file'"`
newly assertion tool assert_no_diff makes intention clearer by using the following syntax:
`assert_no_diff "path/to/expected file" "path/to/generated file"`
goal is to make visible that:
- what is expected is that there is no difference
- what is compared are two files

add new assert_no_diff assertion directive

---

README.adoc
bash_unit
tests/test_core.sh

@stuertz has provided a code fragment to provide an `assert_matches` assertion in the description of issue #80. There was no pull request yet, so I have included the code now into `bash_unit` and added the counterpart `assert_not_matches` as well. Tests have been added to `tests/test_core.sh` for both assertions. The documentation in `README-adoc` has been extended by the two new assertions, including the corresponding tests.
Many thanks to Jan for his initial contribution, this was a missing assertion I currently was looking for.

enh: added assert_matches and assert_not_matches, fixes Issue 80

---

README.adoc

Some fixes to the documentation:
* Removed some markers around the new `assert_matches` and `assert_not_matches` documentation sections. 
* Added the missing description for `assert_no_diff`.
Note that I have not added the generated man page, as I just had a down level version of `asciidoctor` in my WSL ubuntu setup available.
Regards,
Christian

docs: fix assert_(not_)matches, added matches_no_diff

---

README.adoc
bash_unit
tests/test_core.sh

Fixes https://github.com/pgrange/bash_unit/issues/87
Tripped on this issue while doing some tests and ended up sorting it out.
Note: this has the risk to break some tests for users, but I think this is a more correct way of preserving the arguments in the long run. The docs reflect the difference in usage.
Thanks for your work,
João

Pass params as array

---

README.adoc
bash_unit
tests/test_core.sh

```
assert_within_delta <expected num> <actual num> <max delta>
```
Given an expectation of 5 and a delta of 2 this would match 3, 4, 5, 6, and 7

assert number equality within delta

---

bash_unit
release

Fixes in bash_unit to compensate for most shellcheck message except some case where more analysis is needed.

Fix bash_unit - most shellcheck messages

---

install.sh

- Bug: the variable used to cleanup the tmp_dir was wrong.
- Cosmetics: Improvement for a more robust script.

Fix the install script

---

README.adoc
bash_unit
getting_started/hello_i18n
getting_started/hello_timed
getting_started/tests/test_hello_i18n
release
tests/test_cli.sh
tests/test_core.sh

This makes some minor cleanups (detected by the tools setup in the pre-commit configuration) related to whitespace, typos and automatic shellscript formatting.

Qual: Fix typos, whitespace, beautysh

---

.github/workflows/pre-commit.yml
.pre-commit-config.yaml

This is an update to the pre-commit configuration so that it uses the hook proposed in this repository.
I used a specific commit has as there is/was no regular tag yet.
This alos shows a limitation of pre-commit: only changed files are provides as arguments and there is no option to automatically propose all files matching the regex.
Howevert that means that one could execute bash_unit on a test that changed automatically.
As shown in the integration setup, it's still possible to run on all files usin the '-a/--all-files' option.  The other solution is to use the 'args:' parameter in the hook configuration.

Calling bash-unit pre-commit hook in ci + sample setup

---

tests/test_core.sh
tests/test_doc.sh

We observed broken pipe output messages with bash_unit test in some environments: github CI and nix builds. The tests are passing but display this suspiscious error message.
@Pamplemousse has been able to reproduce them locally by trapping SIGPIPE:
```bash
Running tests in tests/test_core.sh
Running test_fail_fails ... /nix/store/11b3chszacfr9liy829xqknzp3q88iji-gnugrep-3.11/bin/grep: write error: Broken pipe
SUCCESS ✓
Overall result: SUCCESS ✓
```
From man, SIGPIPE appears when a process writes on a pipe with no reader. Looking at the problematic tests, we see that they all rely on a muted bash_unit with a stacktrace output being muted.
When we look at how the stacktrace is muted, the code was like this:
```bash
notify_stack () { : ; }
```
And when we look at how the stacktrace is …

Fixes #115

---

install.sh

Fixes #124 
Piping to `head` does not mix with `set -o pipefail` because `head` "short-circuits" as soon as it finds a result, causing a SIGPIPE to be sent to the writer, which may cause the writer to fail.

Fix tarball url parsing in presence of "pipefail"

---

README.adoc
bash_unit
tests/test_tap_format

Hi @ndavies-om1,
This is an updated version of your PR https://github.com/pgrange/bash_unit/pull/131.
This fixes the following issues:
* the documentation did not include your contribution with displaying the plan
* the plan must include skipped/pending tests
I also renamed the variable that points to the file you use to store the test count to TEST_COUNT_FILE and used mktemp to create it.
I close https://github.com/ndavies-om1/bash_unit/pull/2 which is a duplicate of this one.
Best regards,

Add plan to tap output

---

.pre-commit-hooks.yaml
README.adoc
bash_unit
tests/test_core.sh
tests/test_tap_format

Found a couple of minor typos while looking through the code

feat: minor typos

---

bash_unit
tests/test_cli.sh
tests/test_core.sh

This PR implements the fix for the `set -e` behavior, as discussed in #135.

feat: improve `set -e` behaviour
